# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: NetworkManager-libreswan.spec

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: NetworkManager-libreswan
# downstream (Fedora) RPM package name
downstream_package_name: NetworkManager-libreswan
